services:
  jcs-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jcs-backend
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - jcs-network

networks:
  jcs-network: